#*******************************************************************************
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#*******************************************************************************

networks:
  app-net:
    driver: overlay
    attachable: true
  mcu-net:
    driver: overlay
    attachable: true

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.config:/mosquitto/config/mosquitto.conf:ro
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -t 'test/#' -C 1 -E -W 3 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  ustreamer:
    #image: ustreamer:latest
    image: ghcr.io/valtechmobility/up-streamer-rust/configurable-streamer:add_build_and_containerize_pipeline
    ports:
      - "0.0.0.0:7447:7447"
    expose:
      - "7447"
    networks:
      - app-net
    volumes:
      - type: bind
        source: ./config/ustreamer-config
        target: /app/config
    environment:
      - RUST_LOG=debug,zenoh=debug
    depends_on:
      mosquitto:
        condition: service_healthy

  kuksa-databroker:
    container_name: "kuksa-databroker"
    image: ghcr.io/eclipse-kuksa/kuksa-databroker:0.5.0
    command: ["--insecure"]
    restart: unless-stopped
    environment:
      KUKSA_DATABROKER_PORT: "55556"
    ports:
      - "55556:55556"
    networks:
      - "app-net"

  healthchecker:
    image: alpine
    networks:
      - app-net
    command: >
      /bin/sh -c "
        apk add --no-cache netcat-openbsd &&
        while true; do
          nc -zv ustreamer 7447 2>/dev/null || { echo 'Waiting for ustreamer...'; sleep 1; continue; }
          nc -zv kuksa-databroker 55556 2>/dev/null || { echo 'Waiting for kuksa-databroker...'; sleep 1; continue; }
          echo 'All services are up!'
          exit 0
        done"

  vehicle-gateway:
    build:
      context: "./components"
      dockerfile: "Dockerfile.vehicle-gateway"
    image: vehicle-gateway:latest
    networks:
      - app-net
    depends_on:
      healthchecker:
        condition: service_completed_successfully # wait for the healthcheck to succeed
    environment:
      RUST_LOG: "trace"
      ZENOH_CONFIG: "/zenoh-config.json5"
    volumes:
      - "./config/vehicle-gateway-zenoh-config.json5:/zenoh-config.json5"

  horn-client:
    build:
      context: "./components"
      dockerfile: "Dockerfile.horn-client"
    image: horn-client:latest
    networks:
      - app-net
    depends_on:
      healthchecker:
        condition: service_completed_successfully # wait for the healthcheck to succeed
    environment:
      RUST_LOG: "trace"
      MQTT_HOSTNAME: "mosquitto"
      MQTT_PORT: 1883

  horn-service-kuksa:
    build:
      context: "./components"
      dockerfile: "Dockerfile.horn-service"
    container_name: "horn-service-kuksa"
    image: horn-service:latest
    restart: unless-stopped
    depends_on:
      healthchecker:
        condition: service_completed_successfully # wait for the healthcheck to succeed
    networks:
      - "app-net"
    environment:
      RUST_LOG: "trace"
      KUKSA_ADDRESS: "http://kuksa-databroker:55556"
      KUKSA_ENABLED: "true"
      ZENOH_CONFIG: "/zenoh-config.json5"
    volumes:
      - "./config/horn-service-zenoh-config.json5:/zenoh-config.json5"

  zenoh-kuksa-provider:
    container_name: "zenoh-kuksa-provider"
    build:
      context: "./components/kuksa-incubation/zenoh-kuksa-provider"
      dockerfile: Dockerfile
      target: final
    restart: unless-stopped
    volumes:
      - "./config/zenoh-kuksa-provider-config.json5:/provider-config.json5"
    networks:
      - "app-net"
      - "mcu-net"
    environment:
      PROVIDER_CONFIG: "/provider-config.json5"
      RUST_LOG: "INFO"
    depends_on:
      healthchecker:
        condition: service_completed_successfully # wait for the healthcheck to succeed

  software-horn:
    build:
      context: "./components"
      dockerfile: "Dockerfile.software-horn"
    container_name: "software-horn"
    image: software-horn:latest
    restart: unless-stopped
    depends_on:
      - zenoh-kuksa-provider
    networks:
      - "mcu-net"
    environment:
      RUST_LOG: "trace"
      ZENOH_CONFIG: "/zenoh-config.json5"
    volumes:
      - "./config/software-horn-zenoh-config.json5:/zenoh-config.json5"
#  horn-client:
#    build:
#      context: "./components"
#      dockerfile: "Dockerfile.horn-client"
#    container_name: "horn-client"
#    image: horn-client:latest
#    restart: unless-stopped
#    environment:
#      HORN_ADDRESS: "tcp/horn-service-kuksa:15000"
#    depends_on:
#      - horn-service-kuksa
